name: Build Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-electron:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x]
        python-version: ['3.12.0']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install Node dependencies
        run: npm ci

      - name: Install Python dependencies
        run: |
          cd flask-backend
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Set up Docker for Linux builds
        if: matrix.os == 'ubuntu-latest'
        uses: docker/setup-buildx-action@v3

      - name: Build Python backend with PyInstaller (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          docker run --rm -v $(pwd):/app -w /app quay.io/pypa/manylinux2014_x86_64 bash -c "
            /opt/python/cp310-cp310/bin/pip install -r flask-backend/requirements.txt pyinstaller
            cd flask-backend
            /opt/python/cp310-cp310/bin/pyinstaller \
              --onefile \
              --collect-all werkzeug \
              --collect-all flask \
              --hidden-import=flask.cli \
              app.spec
          "

      - name: Build Python backend with PyInstaller (Windows/macOS)
        if: matrix.os != 'ubuntu-latest'
        run: |
          cd flask-backend
          # Add runtime hooks to ensure library compatibility
          mkdir -p runtime_hooks
          echo 'import os, sys' > runtime_hooks/hook.py
          echo 'sys.path.insert(0, os.path.join(sys._MEIPASS))' >> runtime_hooks/hook.py
          
          # Use PyInstaller with additional options for better compatibility
          pyinstaller --onefile \
            --runtime-hook=runtime_hooks/hook.py \
            --hidden-import=flask.cli \
            app.spec

      - name: Verify Python build output
        run: |
          ls -la flask-backend/dist
        shell: bash

      - name: Fix Windows executable path (Windows only)
        if: matrix.os == 'windows-latest'
        run: |
          sed -i 's/"app")/"app.exe")/g' forge.config.ts
        shell: bash

      - name: Create copy for Windows
        if: matrix.os == 'windows-latest'
        run: |
          copy flask-backend\dist\app.exe flask-backend\dist\app
        shell: cmd

      - name: Build Electron app
        run: npm run make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            out/make/**/*